name: debugger
version: "0.4"
license: "MPL-2.0"
date: 2021-02-13
description: |
    Debugging support for GAP

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/debugger/
readme: README.md
packageinfo: https://gap-packages.github.io/debugger/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/debugger/releases/download/v0.4/debugger-0.4.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Jef21</span>]   <b class='BibAuthor'>Jefferson, C.</b>,
     <i class='BibTitle'>debugger, Debugging support for GAP,
             Version 0.4</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/debugger/">https://gap-packages.github.io/debugger/</a></span>.
    </p>
    

bibtex: |
    @misc{ debugger0.4,
      author =           {Jefferson, C.},
      title =            {{debugger}, Debugging support for GAP, {V}ersion 0.4},
      month =            {Feb},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/debugger/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{debugger/}}},
      printedkey =       {Jef21}
    }

